### ISSUE TITLE
Naming

### ISSUE THREAD

**Issue by Nayels** [incentro-cloud/terraform-google-operations#1]
Make naming explicit.

``` for_each       = { for bucket in var.buckets : x.bucket_id => x } ``` 

Instead of:

https://github.com/incentro-cloud/terraform-google-operations/blob/0c1ac4dab00afdbb8ec47a7089586b6a191ad35f/modules/buckets/main.tf#L30

**Comment by smorenburg** [comment]
Thanks for the feedback. Modified the naming, issue resolved.
